apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
spec:
  type: NodePort
  selector:
    app: mywebsite
  ports:
    - port: 80         # порт сервиса внутри кластера
      targetPort: 80   # порт внутри контейнера
      nodePort: 30080  # внешний порт на ноде (будем ходить сюда)

